# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:android)
#
# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end
#
#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
#
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end
#
#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end
default_platform(:android)

platform :android do
  desc "Build & Upload to Firebase App Distribution"
  lane :deploy_firebase do
    gradle(
      task: "assemble",
      build_type: "Release"
    )
    firebase_app_distribution(
      app: "1:338649658254:android:8d53bc921b1dede24ceadf",
      testers: "ritik@megamindcreations.com, rahulsalaria@megamindcreations.com",
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      release_notes: "New release from Fastlane CI/CD",  # Comma added here
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk"
    )
  end

  desc "Build & Upload to Google Play"
  lane :deploy_playstore do
    gradle(
      task: "bundle",
      build_type: "Release"
    )
    upload_to_play_store(
      track: "internal",
      aab: "app/build/outputs/bundle/release/app-release.aab"
    )
  end
end

