name: Flutter CI/CD demo

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.2"
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Linter
        run: flutter analyze

      - name: Run Tests
        run: flutter test

      - name: Build APK (Release)
        run: flutter build apk --release


      - name: Setup Bundler & Fastlane
        run: |
          cd android
#          export GEM_HOME="$HOME/gems"
#          export PATH="$HOME/gems/bin:$PATH"
          gem install bundler --user-install
          bundle init
          bundle install --path vendor/bundle

#      - name: Setup Bundler & Fastlane
#        run: |
#          cd android
#          gem install bundler
#          bundle init
#          bundle install

      - name: Deploy to Firebase (Android)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: cd android && bundle exec fastlane deploy_firebase

#      - name: Build Release APK
#        run: flutter build apk --release
#
#      - name: Upload APK Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: release-apk
#          path: build/app/outputs/flutter-apk/app-release.apk
#
#      - name: Build AppBundle
#        run: flutter build appbundle --release
#
#      - name: Upload AppBundle Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: release-aab
#          path: build/app/outputs/bundle/release/app-release.aab
#
#      - name: Deploy to Firebase
#        env:
#          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
#        run: cd android && fastlane deploy_firebase

#      - name: Deploy to Play Store (Optional)
#        env:
#          JSON_KEY_FILE: ${{ secrets.GOOGLE_PLAY_JSON }}
#        run: cd android && fastlane deploy_playstore
#
#      - name: Deploy to TestFlight
#        env:
#          APP_STORE_API_KEY: ${{ secrets.APP_STORE_API_KEY }}
#        run: cd ios && fastlane deploy_testflight
